---
- name: Update UFW Firewall Rules on Deployed AmneziaWG Servers
  hosts: deployed_Awireguard_servers
  become: true

  tasks:
    - name: Remove SSH access from all sources (delete port 22/tcp allow rule)
      shell: "ufw delete allow 22/tcp"
      ignore_errors: yes

    - name: Allow all traffic from specific VPN server IP
      shell: "ufw allow from 38.180.244.244 comment 'VPN server IP'"
      ignore_errors: yes
