---
- name: Update AmneziaWG Server Services
  hosts: servers_to_update
  become: true
  vars:
    # Paths from main setup playbook
    api_dir: "/etc/amnezia/amneziawg/vpn_api"
    scripts_dir: "/etc/amnezia/amneziawg/scripts"

  tasks:
    # --- Update API Server ---
    - name: Copy updated server.js
      copy:
        src: "api/server.js"
        dest: "{{ api_dir }}/server.js"

    - name: Restart API with PM2 (service 0)
      shell: |
        pm2 restart 0
        pm2 save
      environment:
        PATH: "/usr/bin:/bin:/usr/local/bin"

    # --- Update Python Scripts ---
    - name: Copy updated next_available_ip.py
      copy:
        src: "scripts/next_available_ip.py"
        dest: "{{ scripts_dir }}/next_available_ip.py"
        mode: '0755'

    # --- Update Shell Scripts ---
    - name: Copy updated add_peer.sh
      copy:
        src: "scripts/add_peer.sh"
        dest: "{{ scripts_dir }}/add_peer.sh"
        mode: '0755'

    # --- Remove Old Shell Scripts ---
    - name: Remove next_available_ip.sh
      file:
        path: "{{ scripts_dir }}/next_available_ip.sh"
        state: absent

    - name: Verify services are running
      shell: |
        pm2 status
      register: pm2_status
      changed_when: false

    - name: Display PM2 Status
      debug:
        msg: "{{ pm2_status.stdout }}"
